services:
  # =====================
  # DATABASE
  # =====================
  database:
    image: postgres:15-alpine
    container_name: activity_manager_db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha_aqui
      POSTGRES_DB: activity_manager

    ports:
      - "5433:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d activity_manager"]
      interval: 5s
      timeout: 5s
      retries: 5

  # =====================
  # BACKEND
  # =====================
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile

    container_name: activity_manager_backend

    restart: always

    working_dir: /app/apps/backend

    environment:
      PORT: 3000

      DATABASE_URL: postgresql://postgres:sua_senha_aqui@database:5432/activity_manager?schema=public

    ports:
      - "3000:3000"

    depends_on:
      database:
        condition: service_healthy

    command: >
      sh -c "
        pnpm exec prisma generate &&
        pnpm exec prisma migrate deploy &&
        pnpm exec prisma db seed &&
        pnpm start:dev
      "

    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]

      interval: 10s
      timeout: 5s
      retries: 5

  # =====================
  # FRONTEND
  # =====================
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile

    container_name: activity_manager_frontend

    restart: always

    working_dir: /app/apps/frontend

    environment:
      VITE_API_URL: http://localhost:3000

    ports:
      - "5173:5173"

    depends_on:
      backend:
        condition: service_healthy

volumes:
  pgdata:

  backend_node_modules:

  frontend_node_modules:
